name: Run unit tests

on: [pull_request]
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest',]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'

    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: HIERARCHSIR
        environment-file: hierarchSIR_env.yml
        auto-activate-base: false

    - name: Install hierarchSIR 
      shell: bash -l {0}
      run: |
        conda activate hierarchSIR || (echo "Environment not found, creating..." && conda env create -f hierarchSIR_env.yml && conda activate hierarchSIR)
        python -m pip install --upgrade pip
        pip install -e . --force-reinstall

    - name: Run unit test
      shell: bash -l {0}
      run: |
        conda activate hierarchSIR
        pytest src/tests/test_lpp.py
